#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#i_full_restake_decrease_hook;
pub mod r#i_full_restake_reset_hook;
pub mod r#i_network_restake_decrease_hook;
pub mod r#i_network_restake_redistribute_hook;
pub mod r#i_network_restake_reset_hook;
pub mod r#i_operator_specific_decrease_hook;
pub mod r#i_operator_specific_reset_hook;
